CREATE TABLE STUDENT 
( USER_NAME VARCHAR (10)  NOT NULL
, PASSWORD VARCHAR (10)
, PROVINCE VARCHAR (10)
, GENDER VARCHAR (10) 
, HOBBIES VARCHAR (10)
 );
 
INSERT INTO STUDENT VALUES('ZhouYu','111','Shanghai','male','Game');
INSERT INTO STUDENT VALUES('Tom','123','','male','Mouse');